# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'hounddd.calendar::lang.models.event.label'

# Model Form Field configuration
form: $/hounddd/calendar/models/event/fields.yaml

# Model Class name
modelClass: Hounddd\Calendar\Models\Event

# Default redirect location
defaultRedirect: hounddd/calendar/events

# Create page
create:
    title: backend::lang.form.create_title
    redirect: hounddd/calendar/events/update/:id
    redirectClose: hounddd/calendar/events

# Update page
update:
    title: backend::lang.form.update_title
    redirect: hounddd/calendar/events
    redirectClose: hounddd/calendar/events

# Preview page
preview:
    title: backend::lang.form.preview_title
